config/routes.rb
Rails.application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'
  root 'main#index'

  mount RailsAdmin::Engine, at: '/admin'

  resources :user_sessions

  match 'login', to: 'user_sessions#new', via: :get
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  include Taggable

  has_many :media, -> { order(order_number: :desc) }, dependent: :destroy
  accepts_nested_attributes_for :media, :allow_destroy => true

  before_save :set_order_number

  enum size: [ :small, :big ]

  mount_uploader :thumbnail, ThumbnailUploader

  scope :published, -> { where(is_published: true).order('order_number DESC, created_at DESC') }

  validates_presence_of :name, :size

  def interactive?
    media.first.link.present?
  end

  def set_order_number
    if self.order_number.blank?
      self.order_number = Brand.all.order('order_number DESC').first.order_number
    end
  end
end

app/models/concerns/taggable.rb
module Taggable
  extend ActiveSupport::Concern

  included do
    has_many :taggings, as: :taggable
    has_many :tags, through: :taggings
  end

  def tag_names
    tags.map(&:name)
  end
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :medium
  belongs_to :position
end

app/models/medium.rb
class Medium < ActiveRecord::Base
  include Taggable

  mount_uploader :thumbnail, ThumbnailUploader

  belongs_to :brand
  has_many :credits, -> { order(order_number: :desc) }, dependent: :destroy

  scope :published, -> { where(is_published: true).order('order_number DESC, created_at DESC') }

  accepts_nested_attributes_for :credits, allow_destroy: true
end

app/models/news.rb
class News < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  scope :published, -> { where(is_published: true).order('created_at DESC') }

  validates_presence_of :content, :picture
end

app/models/page.rb
class Page < ActiveRecord::Base
  enum category: [ :about ]

  def self.about_text
    where(category: Page.categories[:about]).first.try(:text)
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :brands, through: :taggings, source: :taggable, source_type: 'Brand'
  has_many :media, through: :taggings, source: :taggable, source_type: 'Medium'

  validates :name, presence: true, uniqueness: true

  enum kind: [ :project, :credit ]
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :taggable, polymorphic: true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
end

app/models/video.rb
class Video < ActiveRecord::Base
  include Taggable

  before_save :set_order_number

  enum size: [ :small, :big ]

  mount_uploader :thumbnail, ThumbnailUploader

  scope :published, -> { where(is_published: true).order('order_number DESC, created_at DESC') }

  validates_presence_of :name, :music, :vimeo_id, :thumbnail, :size

  def interactive?
    link.present?
  end

  def set_order_number
    if self.order_number.blank?
      self.order_number = Video.all.order('order_number DESC').first.order_number
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :require_login, :except => [:not_authenticated]

  def not_authenticated
    redirect_to main_app.login_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_filter :require_login

  def index
    @brands = Brand.published.select { |brand| brand.media.length > 0 }
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login

  layout 'login'
  
  def new
    @user = User.new
  end
  
  def create
    respond_to do |format|
      if @user = login(params[:username], params[:password])
        format.html { redirect_back_or_to(rails_admin.dashboard_path) }
      else
        format.html { render action: "new" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date.strftime("%d.%m.%Y")
  end

  def video_class(video)
    class_name = video.size

    if video.interactive?
      class_name += " interactive"
    end

    class_name + " wrapper"
  end

  def medium_url(medium)
    if medium.brand.interactive?
      medium.thumbnail_url(:square)
    elsif medium.brand.big?
      medium.thumbnail_url(:main)
    else
      medium.thumbnail_url(:large)
    end
  end

  def brand_categories(brand)
    brand.tags.map(&:name).join(' ')
  end

  def medium_credits(medium)
    medium.tags.map(&:name).join(' & ')
  end

  def position_name(position, credits)
    credits.length > 1 && !position.singular ? position.name.pluralize : position.name
  end

  def medium_subtitle(medium)
    [medium_credits(medium), brand_categories(medium.brand)].select{|x| x.length > 0}.join(" - ")
  end

  def medium_title(medium)
    [medium.brand.name, medium.name].select{|x| x.length > 0}.join(" - ")
  end
end

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title D4ZED
    meta[name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" user-scalable="no"]
    = display_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    script[src="//use.typekit.net/jzv5wsa.js"]
    javascript:
      try{Typekit.load();}catch(e){}
    = render 'ga'

  body.no-transition
    = yield

  = javascript_include_tag 'application'

app/views/layouts/login.html.slim
<!DOCTYPE html>
html
  head
    title D4ZED
    meta[name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" user-scalable="no"]
    = stylesheet_link_tag 'login', media: 'all'

  body
    = yield

app/views/main/_brand.html.slim
div[class=video_class(brand) data-id=brand.id]
  .container
    - if brand.media.published.length > 1
      = render partial: "main/medium", locals: { medium: brand.media.published.last, index: -1, playable: false }
    - brand.media.published.each_with_index do |medium, index|
      = render partial: "main/medium", locals: { medium: medium, index: index, playable: true }
    - if brand.media.published.length > 1
      = render partial: "main/medium", locals: { medium: brand.media.published.first, index: brand.media.published.length, playable: false }
  .info.mobile
    .mobile-container
  - if !brand.interactive?
    button.mobile-player
      i.d4zed-icon-play-standalone
  - else
    button.mobile-link
      = link_to nil, target: "_blank" do
        i.d4zed-icon-link-standalone
  button.expander
    i.d4zed-icon-close
    i.d4zed-icon-expand
  - if brand.media.length > 1
    button.prev
      i.d4zed-icon-chevron-left
    button.next
      i.d4zed-icon-chevron-right

app/views/main/_ga.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', "#{ENV['GA_TRACKER']}", 'auto');
  ga('send', 'pageview');

app/views/main/_medium.html.slim
- brand = medium.brand

article.media[data-index=index data-vimeo-id=medium.vimeo_id id=(playable ? medium.name.gsub(' ', '-').downcase : nil)]
  .animation
    .spinner
      .bounce1
      .bounce2
      .bounce3
  .cover[style="background-image: url(#{medium_url(medium)});"]
  .bg[style="background-color: ##{brand.bg_color};"]
  .gradient
    .cover-info
      - if brand.name.present?
        .brand = brand.name
      .name = medium.name
      .subtitle = medium_subtitle(medium)
  .info.mobile
    .credits
      - medium.credits.group_by(&:position).each do |position, credits|
        - if position
          h2 = position_name(position, credits)
          - credits.each do |credit|
            p = credit.person
  .info.desktop
    header = "#{medium_title(medium)} (#{medium_subtitle(medium)})"
    p = medium.description.html_safe
    table.desktop
      - medium.credits.map { |credit| { position: credit.position, person: credit.person } }.group_by{ |credit| credit[:position] }.values.in_groups_of(2).each do |group|
        tr
          - group.each do |credits|
            td
              - if credits.present? && credits[0][:position]
                h4 = position_name(credits[0][:position], credits)
                - credits.each do |credit|
                  p = credit[:person]

    - if playable
      - if brand.interactive?
        = link_to "", medium.link, target: "_blank", class: "link"
      - else
        .player

app/views/main/index.html.slim
- description = Nokogiri::HTML.parse(Page.about_text).css('p').first.try(:text)

- set_meta_tags description: description, image: image_url('logo.png'), canonical: "http://d4zed.com"

- set_meta_tags twitter: { title: "D4ZED", type: "article", image: image_url('logo.png'), description: description, url: "http://d4zed.com", site_name: "D4ZED", site: "@d_4_z_e_d", creator: "@d_4_z_e_d", card: image_url('logo.png') }
- set_meta_tags og: { title: "D4ZED", type: "article", image: image_url('logo.png'), description: description, url: "http://d4zed.com", site_name: "D4ZED" }

header
  .header-wrapper
    .wrapper
      = link_to "", class: "root-link" do
        = image_tag "logo.svg", class: "logo"
      ul.menu
        li = link_to "Work", "#work"
        li = link_to "About", "#about", :"data-load-all" => true
        li = link_to "Contact", "#contacts", :"data-load-all" => true
        li.social-links
          = link_to "https://www.facebook.com/D4ZEDD4ZED", target: "_blank" do
            i.d4zed-icon-facebook
          = link_to "https://twitter.com/d_4_z_e_d", target: "_blank" do
            i.d4zed-icon-twitter
      ul.social
        li = link_to "https://www.facebook.com/D4ZEDD4ZED", target: "_blank" do
          i.d4zed-icon-facebook
        li = link_to "https://twitter.com/d_4_z_e_d", target: "_blank" do
          i.d4zed-icon-twitter
      button.mobile-menu-button
        .d4zed-navicon
          .bar
          .bar
          .bar

#main
  .wrapper

    section#work
      - @brands.each do |brand|
        - if brand.media.published.size > 0
          = render partial: "main/brand", locals: { brand: brand }

    footer
      section#about
        .wrapper
          .content = Page.about_text.try(:html_safe)

      section#contacts
        .wrapper
          .column
            = link_to "hello@d4zed.com", "mailto:hello@d4zed.com"
            br
            br
            | Vesterbrogade 62D
            br
            | 1620 Copenhagen
            br
            | Denmark
            br
            | +45 60601221
          .column
            br
            br
            | 843 1/2 Palms Blvd
            br
            | Venice, CA 90291
            br
            | United States
            br
            | +1 (213) 457-3385

app/views/user_sessions/new.html.slim
h1 Login

= form_tag user_sessions_path, method: :post do
  div.form-group
    = label_tag :username
    = text_field_tag :username, '', class: "form-control"
  div.form-group
    = label_tag :password
    = password_field_tag :password, '', class: "form-control"

  div.actions
    = submit_tag "Login", class: 'btn btn-primary'